name: dash_board
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.0.0
  intl_phone_number_input: ^0.7.1
  intl_phone_field: ^1.3.0
  pin_code_fields: ^7.4.0
  flutter_const: ^0.0.7
  pinput: ^2.2.16
  provider: ^6.0.4
  google_maps_flutter: ^2.2.1
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.2
  fdottedline_nullsafety: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - images/img.png
      - images/img_3.png
      - images/img_4.png
      - images/img_5.png
      - images/img_6.png
      - images/img_7.png
      - images/img_8.png
      - images/img_9.png
      - images/img_10.png
      - images/img_11.png
      - images/img_12.png
      - images/img_13.png
      - images/img_14.png
      - images/img_15.png
      - images/img_17.png
      - images/img_18.png
      - images/img_19.png
      - images/img_20.png
      - images/img_23.png
      - images/img_24.png
      - images/img_25.png
      - images/img_26.png
      - images/img_27.png
      - images/img_28.png
      - images/img_29.png
      - images/img_30.png
      - images/img_31.png
      - images/img_32.png
      - images/img_33.png
      - images/img_38.png
      - images/img_39.png
      - images/img_40.png
      - images/img_41.png
      - images/img_42.png
      - images/img_43.png
      - images/img_44.png
      - images/img_45.png
      - images/img_46.png
      - images/img_47.png
      - images/img_48.png
      - images/img_49.png
      - images/img_50.png
      - images/img_53.png
      - images/img_54.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
